import Head from "next/head";
import { Inter } from "next/font/google";
import {Main} from "../components/main"

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main className={styles.main}> */}
        {/* <div className={styles.description}> */}
          {/* <Headline */}
            {/* // 文字列 */}
            {/* page="about" */}
            {/* // 数値 */}
            {/* // number={11111} */}
            {/* // 配列 */}
            {/* // array={[1, 2, 3]} */}
            {/* // オブジェクト */}
            {/* // obj={{ foo: "foo", bar: "bar" }} */}
            {/* // 真偽値 */}
            {/* // boolean */}
          {/* > */}
          {/* コンポーネント */}
            {/* code={<code className={styles.code}>pages/about.js</code>} */}
          {/* </Headline> */}
          {/* <Header /> */}
        {/* </div> */}
        {/* <MainTitle maintitle="about" /> */}
        {/* <h1>ABOUT PAGE</h1> */}
        {/* <Logo /> */}
        {/* <Link /> */}
      {/* </main> */}

      <Main page="about"/>
    </>
  );
}
