import Head from 'next/head'
import { Inter } from 'next/font/google'
import {Main} from "../components/main"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

{/* コンポーネント化 */}
      {/* <main className={styles.main}> */}
        {/* <div className={styles.description}> */}
          {/* <Headline */}
            {/* page="index"  */}
            {/* // code={<code className={styles.code}>pages/index.js</code>} */}
            {/* // onClick={() => alert("クリックU^ｪ^U")} */}
          {/* > */}
          {/* childrenで書き換え */}
          {/* コンポーネント */}
          {/* <code className={styles.code}>pages/index.js</code> */}
          {/* 閉じタグ必要 */}
          {/* </Headline> */}
          {/* <Header /> */}
        {/* </div>     */}
        {/* <MainTitle maintitle="index" /> */}
        {/* <h1>INDEX PAGE</h1>          */}
        {/* <Logo /> */}
        {/* <Link />         */}
      {/* </main> */}

      <Main page="index"/>
    </>
  )
}
