import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {Logo} from "../components/logo"
import {Header} from "../components/header"
import {Link} from "../components/link"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.description}>

          <p>
          🐣🐣🐣🐣🐣🐣Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>

          <Header />

        </div>

        <h1>INDEX PAGE</h1>

        <Logo />

        <Link />
        
      </main>
    </>
  )
}
